version: '3.8'

services:

  mongo:
    container_name: mongo-docker-server
    image: mongo
    restart: always
    expose:
      - '27017'
    ports:
      - 8081:8081
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    volumes:
    - C:\MongoData\DockerMongo:/data/db:cached